# ------------------------------------
# GITHUB COMMAND LINE INTERFACE CONFIG
# ------------------------------------

git_protocol: ssh
editor: vim
pager: less
prompt: enabled
aliases:
    co: pr checkout
    show: repo view --web
    bugs: issue list --label="bugs"
