#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
export PATH=$HOME/.local/bin:$PATH
export HISTCONTROL=ignoreboth:erasedups

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ls='ls --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -lA --color=auto'
alias rm='rm -i'
alias mv='mv -i'
alias c='clear'
alias :wq='exit'

# Exports to match XDG base directory specification
export XDG_CONFIG_HOME=/home/piotr/.config
export XDG_CACHE_HOME=/home/piotr/.cache
export XDG_DATA_HOME=/home/piotr/.local/share

export ERRFILE="$XDG_CACHE_HOME"/xsession-errors
export PYLINTHOME="$XDG_DATA_HOME"/pylint
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; personal $XDG_CONFIG_HOME/aspell/pl.pws; personal $XDG_CONFIG_HOME/aspell/en.pws; repl $XDG_CONFIG_HOME/aspell/pl.prepl; repl $XDG_CONFIG_HOME/aspell/en.prepl;"
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME"/bash-completion/bash_completion
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle 
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle 
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npmrc
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship.toml
export HISTFILE="$XDG_DATA_HOME"/bash/history
export GNUPGHOME="$XDG_DATA_HOME"/gnupg

# Vi keybindings
set -o vi
bind 'set show-mode-in-prompt on'
bind 'set vi-cmd-mode-string "\1\e[2 q\2"'
bind 'set vi-ins-mode-string "\1\e[6 q\2"'

# Prompt and window title
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
eval "$(starship init bash)"
